### ISSUE TITLE
missing marker \it...\it*

### ISSUE THREAD

**Issue by ngaretou** [WycliffeAssociates/USFMVSCode#8]
Hi Wycliffe Associates, I use your Visual Code extension, thanks for making it available! 

I wanted to alert you to a missing marker, \it, that it is not yet aware of and marks as wrong.

[\it …\it* on USFM reference](https://ubsicap.github.io/usfm/characters/index.html#it-it)

Thanks!

**Comment by rbnswartz** [comment]
Hi @ngaretou thanks for letting us know, I just pushed a new version of the extension that adds support for the \it and \it* markers
