### ISSUE TITLE
couple of missing markers

### ISSUE THREAD

**Issue by ngaretou** [WycliffeAssociates/USFMVSCode#9]
Hello again USFMVSCode team, 

Just reporting a couple of missing tags coming up in working on some USFM files: 

- fq*: fq is recognized but the closing fq* is not
  - fq* is not in the official documentation, only fq, although Paratext is fine with it. 
  - https://ubsicap.github.io/usfm/notes_basic/fnotes.html#fq
- im is not recognized
  - https://ubsicap.github.io/usfm/introductions/index.html#im

Thanks again for this great extension!

**Comment by rbnswartz** [comment]
This should be resolved in version 0.2.1 that I just released
